clear;
clc;
addpath("../Rx")
addpath("../Tx")

R = '1/2';
MSC = '16-QAM';
ppdu_length = 2000;
FC = '08013000';
MAC1 = 'BEAC09BEAC09';
MAC2 = 'BEAC08BEAC08';
MAC3 = 'BEAC07BEAC07';
TIME_STAMP = 1000;
complex_data = top_tx(...
    R,MSC,...
    ppdu_length,...
    FC,...
    MAC1,MAC2,MAC3,...
    TIME_STAMP...
    );

complex_data = [zeros(100,1);complex_data;zeros(100,1)];

[...
    PKT_STARTr,PKT_ENDr,...
    MSCr,Rr,...
    PPDU_LENGTHr,...
    PKT_TYPEr,...
    MAC1r,MAC2r,MAC3r,...
    TIME_STAMPr...
    ] = top_rx(complex_data);



